Bump major versions
freechipsproject/chisel-testers pull request #302
Opened 2020-11-10 21:47 UTC by azidar

2020-11-10 21:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/freechipsproject/chisel-testers?pullRequest=302) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/freechipsproject/chisel-testers?pullRequest=302) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/freechipsproject/chisel-testers?pullRequest=302) it.</sub>

2020-11-11 02:07 UTC, jackkoenig commented
This repo apparently doesn't have CI...

2020-11-13 17:25 UTC, chick requested changes
I think you need to change the version number for chisel-testers to 1.6-SNAPSHOT
Or is this being done somewhere else

2020-11-19 17:11 UTC, chick approved these changes
lgtm

2020-11-23 22:05 UTC, merged